# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/OneDrive_2025-04-23/RISCV CPU/PotatoCPU/PotatoCPU.srcs/sources_1/bd/zynqTOclkwizard/ip/zynqTOclkwizard_zynq_ultra_ps_e_0_0/zynqTOclkwizard_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'zynqTOclkwizard_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive_2025-04-23/RISCV CPU/PotatoCPU/PotatoCPU.gen/sources_1/bd/zynqTOclkwizard/ip/zynqTOclkwizard_zynq_ultra_ps_e_0_0/zynqTOclkwizard_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqTOclkwizard_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/OneDrive_2025-04-23/RISCV CPU/PotatoCPU/PotatoCPU.gen/sources_1/bd/zynqTOclkwizard/ip/zynqTOclkwizard_zynq_ultra_ps_e_0_0/zynqTOclkwizard_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqTOclkwizard_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/OneDrive_2025-04-23/RISCV CPU/PotatoCPU/PotatoCPU.srcs/sources_1/bd/zynqTOclkwizard/ip/zynqTOclkwizard_zynq_ultra_ps_e_0_0/zynqTOclkwizard_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'zynqTOclkwizard_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive_2025-04-23/RISCV CPU/PotatoCPU/PotatoCPU.gen/sources_1/bd/zynqTOclkwizard/ip/zynqTOclkwizard_zynq_ultra_ps_e_0_0/zynqTOclkwizard_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqTOclkwizard_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/OneDrive_2025-04-23/RISCV CPU/PotatoCPU/PotatoCPU.gen/sources_1/bd/zynqTOclkwizard/ip/zynqTOclkwizard_zynq_ultra_ps_e_0_0/zynqTOclkwizard_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqTOclkwizard_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
