# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/avnet.xdc

# Block Designs: bd/zynqTOclkwizard/zynqTOclkwizard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynqTOclkwizard || ORIG_REF_NAME==zynqTOclkwizard} -quiet] -quiet

# IP: bd/zynqTOclkwizard/ip/zynqTOclkwizard_zynq_ultra_ps_e_0_0/zynqTOclkwizard_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynqTOclkwizard_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zynqTOclkwizard_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zynqTOclkwizard/ip/zynqTOclkwizard_clk_wiz_0_0/zynqTOclkwizard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynqTOclkwizard_clk_wiz_0_0 || ORIG_REF_NAME==zynqTOclkwizard_clk_wiz_0_0} -quiet] -quiet

# XDC: e:/GIt/RISC-V-CPU/PotatoCPU/PotatoCPU.gen/sources_1/bd/zynqTOclkwizard/zynqTOclkwizard_ooc.xdc
