# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.srcs/sources_1/ip/aee_rom/aee_rom.xci
# IP: The module: 'aee_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/aee_rom/aee_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aee_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.srcs/sources_1/ip/aee_rom/aee_rom.xci
# IP: The module: 'aee_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/aee_rom/aee_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aee_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
