# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.srcs/sources_1/ip/clock_generator/clock_generator.xci
# IP: The module: 'clock_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.srcs/sources_1/ip/clock_generator/clock_generator.xci
# IP: The module: 'clock_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GIt/RISC-V-CPU/KPU_vol1/KPU_vol1.gen/sources_1/ip/clock_generator/clock_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
